name: les Actions en detail
on: [push]
env:
  NIVEAU_WORKFLOW: "Je suis une variable de workflow"

jobs:
  mon_job:
    runs-on: ubuntu-latest
    env:
      NIVEAU_JOB: "Je suis une variable de job"
    steps:
      - name: Étape 1
        env:
          NIVEAU_ETAPE: "Je suis une variable d'étape"
        run: |
          echo "$NIVEAU_WORKFLOW"
          echo "$NIVEAU_JOB"
          echo "$NIVEAU_ETAPE"
          echo "$NIVEAU_REPO"
          echo "$NIVEAU_SECRET_REPO"
      - name: List all environment variables
        run: env