name: CI/CD pour Node.js

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: installe les dépendances
      run: npm install

    - name: exécute les tests
      run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && success() }}

    steps:
    - name: déploiement sur serveur de production
      run: ./deploy.sh