name: les Actions en detail
on: [push]
jobs:
  Explorer-Actions-Github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # with :
        #   sparse-checkout: |
        #     .github
      - run: ls -la