name: l'utilisation des contexts pour les variables
on: [push]
env:
  NIVEAU_WORKFLOW: "Je suis une variable de workflow"

jobs:
  mon_job:
    runs-on: ubuntu-latest
    env:
      NIVEAU_JOB: "Je suis une variable de job"
    steps:
      - name: ${{ env.NIVEAU_WORKFLOW }} #context env remplacerment avant execution
        env:
          NIVEAU_ETAPE: "Je suis une variable d'étape"
        run: |
          echo "$NIVEAU_WORKFLOW"
          echo "$NIVEAU_JOB"
          echo "$NIVEAU_ETAPE"
          echo ${{vars.NIVEAU_REPO}}
          echo ${{secrets.NIVEAU_SECRET_REPO}}
      